---
title: "R_MD_dplyr"
author: "JN-0"
date: "2019年6月19日"
output: html_document
---

```{r}
library(tidyverse)
D <- read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')
```

**filter**
**select**
**mutate**
**summarise**
**arrange**


```{r}
#### filter
filter(D, lifeExp < 35); filter(D, country == 'Mexico')
mean(filter(D, country == 'Brazil', 1986 < year, year < 2008)$lifeExp)

sub1 <- filter(D, country == 'Brazil', 1986 < year)
sub2 <- filter(sub1, country == 'Brazil', year < 2008)
```

```{r}
#### select
select(D, year, country, lifeExp)
select(D, -continent, -lifeExp)

D_Cambodia1 <- filter(D, country == 'Cambodia')
D_Cambodia2 <- select(D, -continent, -lifeExp)

gap <- filter(D, country == 'Cambodia') %>% select(-continent, -lifeExp)

gap1 <- D %>% 
  filter(country == 'Cambodia') %>% 
  select(-continent, -lifeExp)

```

```{r}
#### mutant
D %>% 
  mutate(gdp = pop * gdpPercap)

D_Asia_pop <- D %>% 
  filter(year == 2007, continent == 'Asia') %>% 
  mutate(D_Aisa_pop = pop/1000)


```

#### group_by + summarise
```{r}
#### group_by + summarise
D %>% 
  filter(year == 2002) %>% 
  group_by(continent) %>% 
  mutate(cont_pop = sum(pop))

D %>% 
  filter(year == 2002) %>% 
  group_by(continent) %>% 
  summarize(cont_pop = sum(pop))

df <- D %>% 
  group_by(continent, year) %>% 
  summarize(cont_pop = sum(pop))

df <- D %>% 
  group_by(continent, year) %>% 
  summarize(cont_pop = sum(pop)) %>% 
  ungroup
```




```{r}

D %>% 
  group_by(continent, year) %>% 
  mutate(GDP = pop * gdpPercap)
  

D %>% 
  group_by(continent, year) %>% 
  summarize(cont_gdp = sum(gdpPercap))


```









```{r}
D %>% 
  group_by(continent, year) %>% 
  summarize(cont_pop = sum(pop)) %>% 
  arrange(year)


D %>% 
  group_by(continent, year) %>% 
  summarize(cont_gdp = sum(gdpPercap))


D %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  group_by(continent) %>% 
  mutate(maxgdp = max(gdp)) %>% 
  filter(gdp == maxgdp)






```






















```{r}


```